### ISSUE TITLE
pysswords throws a nasty error on --show-password

### ISSUE THREAD

**Issue by betarelease** [marcwebbie/pysswords#6] opened 2015-01-08 20:34 UTC
I have one test entry in the database but on showpassword it throws and error.

| name   | login       | password   | comments                |
|--------+-------------+------------+-------------------------|
| github | betarelease | ****       | this is github password |

pysswords --show-password

Database passphrase: 
Traceback (most recent call last):
  File "/usr/local/bin/pysswords", line 5, in <module>
    runpy.run_module("pysswords", run_name="__main__")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 223, in <module>
    run()
  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 219, in run
    show_password=args.show_password)
  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 113, in list_credentials
    row = build_row(database, credential, show_password)
  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 95, in build_row
    check_passphrase(database, passphrase)
  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 82, in check_passphrase
    default_key=database.key,
  File "/Library/Python/2.7/site-packages/pysswords/db.py", line 32, in key
    return self.gpg.list_keys(secret=True)[0]["fingerprint"]
IndexError: list index out of range

**Comment by marcwebbie** [comment] 2015-01-08 22:45
Did you initialize the database with? 

`pysswords --init`

I am working on getting a better feedback than this error.  Thank you!

**Comment by betarelease** [comment] 2015-01-08 23:39
This is all that I did.. although notice "sudo pip install...."
------------------------------------------------------------------------------------------------------------------------------------
 $ sudo pip install pysswords

 $ pysswords --init

Database passphrase:

Type again:

 $ pysswords -a

Name: github

Login: betarelease

Credential password:

Type again:

Comments [optional]: this is github password

 $ pysswords -g github

Credential(name=github, login=betarelease)

 $ pysswords

| name   | login       | password   | comments                |

|--------+-------------+------------+-------------------------|

| github | betarelease | ****       | this is github password |

 $ pysswords --show-password

Database passphrase:

Traceback (most recent call last):

  File "/usr/local/bin/pysswords", line 5, in <module>

    runpy.run_module("pysswords", run_name="__main__")

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py",
line 180, in run_module

    fname, loader, pkg_name)

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py",
line 72, in _run_code

    exec code in run_globals

  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 223,
in <module>

    run()

  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 219,
in run

    show_password=args.show_password)

  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 113,
in list_credentials

    row = build_row(database, credential, show_password)

  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 95,
in build_row

    check_passphrase(database, passphrase)

  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 82,
in check_passphrase

    default_key=database.key,

  File "/Library/Python/2.7/site-packages/pysswords/db.py", line 32, in key

    return self.gpg.list_keys(secret=True)[0]["fingerprint"]

IndexError: list index out of range

On Thu, Jan 8, 2015 at 2:45 PM, Marc Webbie <notifications@github.com>
wrote:

> Did you initialize the database with?
>
> pysswords --init
>
> I am working on getting a better feedback than this error. Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcwebbie/pysswords/issues/6#issuecomment-69264180>.
>



-- 
Sudhindra.
@sudhindraRao

**Comment by marcwebbie** [comment] 2015-01-09 00:12
It looks like Pysswords is not creating GPG keys in your system...

What is the output for those commands:

`gpg --version`

`gpg2 --version`

`ls ~/.pysswords`

`ls ~/.pysswords/.gnupg`

**Comment by betarelease** [comment] 2015-01-09 04:14
Here you go. I have not installed gpg2..

$ gpg --version

gpg (GnuPG) 1.4.18

Copyright (C) 2014 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>

This is free software: you are free to change and redistribute it.

There is NO WARRANTY, to the extent permitted by law.


Home: ~/.gnupg

Supported algorithms:

Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA

Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,

        CAMELLIA128, CAMELLIA192, CAMELLIA256

Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224

Compression: Uncompressed, ZIP, ZLIB, BZIP2

 $ gpg2 --version

-bash: gpg2: command not found



$ ls ~/.pysswords/

github

$ ls ~/.pysswords/.gnupg/

pubring.gpg secring.gpg trustdb.gpg

On Thu, Jan 8, 2015 at 4:12 PM, Marc Webbie <notifications@github.com>
wrote:

> It looks like Pysswords is not creating GPG keys in your system...
>
> What is the output for those commands:
>
> gpg --version
>
> gpg2 --version
>
> ls ~/.pysswords
>
> ls ~/.pysswords/.gnupg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcwebbie/pysswords/issues/6#issuecomment-69273832>.
>



-- 
Sudhindra.
@sudhindraRao

**Comment by marcwebbie** [comment] 2015-01-10 15:11
Thanks for the feedback I will investigate more to reproduce here and push a fix for next minor version.

**Comment by betarelease** [comment] 2015-01-10 16:15
Thanks. I really like the tool. I just want it to work.

Sudhindra.

On Sat, Jan 10, 2015 at 7:11 AM, Marc Webbie <notifications@github.com>
wrote:

> Thanks for the feedback I will investigate more to reproduce here and push
> a fix for next minor version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcwebbie/pysswords/issues/6#issuecomment-69458922>.
>



-- 
Sudhindra.
@sudhindraRao

**Comment by marcwebbie** [comment] 2015-01-10 17:51
One last thing,

what pysswords version you have?

`pysswords --version`

**Comment by betarelease** [comment] 2015-01-11 03:54
Hi Marc, Here is what I get

 pysswords --version

usage: pysswords [-h] [-I] [-d <DATABASE PATH>] [--show-password] [-a]

                 [-r <CREDENTIAL NAME>] [-e <CREDENTIAL NAME>] [-s <QUERY>]

                 [-g <CREDENTIAL NAME>] [-l] [-c] [--gpg <GPG>]

pysswords: error: unrecognized arguments: --version

On Sat, Jan 10, 2015 at 9:51 AM, Marc Webbie <notifications@github.com>
wrote:

> One last thing,
>
> what pysswords version you have?
>
> pysswords --version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcwebbie/pysswords/issues/6#issuecomment-69464768>.
>



-- 
Sudhindra.
@sudhindraRao

**Comment by marcwebbie** [comment] 2015-01-12 06:19
I see, then you are probably using an older version of [Pysswords](http://marcwebbie.io/pysswords)

Pysswords is now on version 0.0.8. Update it to a newer version:

`sudo pip install -U pysswords`

Check if it is version 0.0.8

`pysswords --version`

[Optional] Remove your old database:

`rm -rf ~/.pysswords`

-------

Then try again.

**Comment by marcwebbie** [comment] 2015-01-14 22:42
Hello @betarelease. Any news on that?

**Comment by betarelease** [comment] 2015-01-14 23:02
I get the following

$ pysswords --version

Pysswords 0.0.8

 $ pysswords --init

Passphrase for database:

Type again:

Traceback (most recent call last):

  File "/usr/local/bin/pysswords", line 11, in <module>

    sys.exit(main())

  File "/Library/Python/2.7/site-packages/pysswords/__main__.py", line 57,
in main

    init=args.init

  File "/Library/Python/2.7/site-packages/pysswords/cli.py", line 20, in
__init__

    self.create_database(path=database_path)

  File "/Library/Python/2.7/site-packages/pysswords/cli.py", line 35, in
create_database

    database = Database.create(path, passphrase)

  File "/Library/Python/2.7/site-packages/pysswords/db/database.py", line
31, in create

    create_keyring(os.path.join(path, ".keys"), passphrase)

  File "/Library/Python/2.7/site-packages/pysswords/crypt.py", line 24, in
create_keyring

    key_input = generate_key_input(path, passphrase)

  File "/Library/Python/2.7/site-packages/pysswords/crypt.py", line 5, in
generate_key_input

    return gnupg.GPG(homedir=path).gen_key_input(

  File "/Library/Python/2.7/site-packages/gnupg/gnupg.py", line 120, in
__init__

    use_agent=use_agent,)

  File "/Library/Python/2.7/site-packages/gnupg/_meta.py", line 158, in
__init__

    self.binary  = _util._find_binary(binary)

  File "/Library/Python/2.7/site-packages/gnupg/_util.py", line 304, in
_find_binary

    raise RuntimeError("GnuPG is not installed!")

RuntimeError: GnuPG is not installed!

$ brew install gnupg

Warning: gnupg-1.4.18_1 already installed

On Wed, Jan 14, 2015 at 2:42 PM, Marc Webbie <notifications@github.com>
wrote:

> Hello @betarelease <https://github.com/betarelease>. Any news on that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcwebbie/pysswords/issues/6#issuecomment-70007435>.
>



-- 
Sudhindra.
@sudhindraRao

**Comment by marcwebbie** [comment] 2015-01-14 23:26
Hello Sudhindra,

Do you manage to create database from the development version?

`pip install --upgrade https://github.com/marcwebbie/pysswords/tarball/master`

**Comment by marcwebbie** [comment] 2015-02-07 16:48
I will be closing the issue for now.

**Closed by marcwebbie** 2015-02-07 16:48 UTC
Labels: bug
